# Generated by Django 5.0.4 on 2024-04-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employees_regid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='percentage',
        ),
    ]
