# Generated by Django 5.0.4 on 2024-04-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_remove_employees_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Company_Name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='From_Date',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Qualification_Name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='To_Date',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='hno',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='street',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='title',
        ),
    ]
