# Generated by Django 5.0.4 on 2024-04-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNo', models.CharField(blank=True, max_length=50, null=True)),
                ('addressDetails', models.TextField()),
                ('hno', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('workExperience', models.TextField()),
                ('Company_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('From_Date', models.CharField(blank=True, max_length=50, null=True)),
                ('To_Date', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.TextField()),
                ('Qualification_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.FloatField()),
                ('projects', models.TextField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.TextField()),
            ],
        ),
    ]
