# Generated by Django 5.0.4 on 2024-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_remove_employees_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='addressDetails',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='projects',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='qualifications',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='workExperience',
            field=models.JSONField(),
        ),
    ]
